Repository ShipSoft/FairShip, pull requests merged in 2024-10, with the labels that each got.

#532 shipStrawTracking: Move to argparse
  CHANGELOG.md
  python/shipStrawTracking.py
Labels: SST, reconstruction

#528 Interfacing EvtCalc in FairShip
  CHANGELOG.md
  macro/convertEvtCalc.py
  macro/run_simScript.py
  shipgen/CMakeLists.txt
  shipgen/EvtCalcGenerator.cxx
  shipgen/EvtCalcGenerator.h
  shipgen/GenLinkDef.h
Labels: enhancement, simulation

#545 Fix missing includes in ecalMatch and ecalReco
  CHANGELOG.md
  ecal/ecalMatch.cxx
  ecal/ecalReco.cxx
Labels: CaloPID
